services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_prod
    networks:
      - fomag-network
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads  # Persistencia para tus escaneos/archivos
    environment:
      - DB_HOST=fomag-sqlserver
      - NODE_ENV=production
      - CORS_ORIGIN=https://arbored-musicologically-adelina.ngrok-free.dev # <--- FIX DE CORS
    restart: unless-stopped

networks:
  fomag-network:
    external: true

volumes:
  uploads_data: